# Generated by Django 3.1.7 on 2021-03-18 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210318_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
        migrations.AddField(
            model_name='task',
            name='due_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 17, 43, 13, 445571)),
        ),
    ]
